host:
  - { name: node1, address: 10.203.1.201, internalAddress: 10.203.1.201, user: root, password: password, root_password: password }
  - { name: node2, address: 10.203.1.202, internalAddress: 10.203.1.202, user: root, password: password, root_password: password }


HAproxy:
  server:
    - { name: node1, port: 6443}
    - { name: node2, port: 6443}

Keepalived:
  host:
    - { name: node1, interface: ens160, priority: 100 }
    - { name: node2, interface: ens160, priority: 80 }
  router_id: TEST_DEVEL
  virtual_router_id: 88
  virtual_ipaddress: 10.203.1.203/32


# spec roleGroups master
KubeKey:
  etcd:
  - node1
  master:
  - node1
  - node2
  worker:
  - node1
  - node2
  address: "10.203.1.203"
  port: 8443
