host:
  - { name: mattie196, address: 10.203.1.196, internalAddress: 10.203.1.196, user: root, password: password, root_password: password, private_ip: 10.203.2.196 }


HAproxy:
  server:
    - { name: mattie196, port: 6443 }

Keepalived:
  host:
    - { name: mattie196, interface: ens160, priority: 100 }
  router_id: TEST_DEVEL
  virtual_router_id: 88
  virtual_ipaddress: 10.203.1.196/32


# spec roleGroups master
KubeKey:
  etcd:
    - mattie196
  master:
    - mattie196
  worker:
    - mattie196
  address: "10.203.1.196"
  port: 8443

VersaSDS:
  vip: 10.203.2.198
  node:
    ip: 10.203.1.185
    root_password: password

ImageVersion:
  console: v0.1.8
  server: v1.0.7